FROM docker.io/archlinux:base-devel

COPY run.sh /run.sh

# makepkg cannot (and should not) be run as root:
RUN useradd -m notroot

# Generally, refreshing without sync'ing is discouraged, but we've a clean
# environment here.
RUN pacman -Syu --noconfirm && \
    pacman -Sy --noconfirm git

# Allow notroot to run stuff as root (to install dependencies):
RUN echo "notroot ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/notroot

# Continue execution (and CMD) as notroot:
USER notroot
WORKDIR /home/notroot

# Auto-fetch GPG keys (for checking signatures):
RUN mkdir .gnupg && \
    touch .gnupg/gpg.conf && \
    echo "keyserver-options auto-key-retrieve" > .gnupg/gpg.conf

# Install yay (for building AUR dependencies):
RUN git clone https://aur.archlinux.org/yay-bin.git && \
    cd yay-bin && \
    makepkg --noconfirm --syncdeps --rmdeps --install --clean

# Configure /etc/makepkg.conf to use more cores and compress using ZSTD
RUN sudo sed -i -e "s/#MAKEFLAGS.*/MAKEFLAGS=\"-j\$(nproc)\"/" \
    -e "s/COMPRESSZST.*/COMPRESSZST=(zstd -c -T0 -18 -)/" \
    -e "s/PKGEXT.*/PKGEXT='.pkg.tar.zst'/" \
    /etc/makepkg.conf && \
    # Enable colored output and an easter egg for pacman
    sudo sed -i "s/#Color/Color\nILoveCandy/" /etc/pacman.conf

# Build the package
WORKDIR /pkg
CMD /bin/bash /run.sh
