FROM docker.io/gradle:jdk11
USER gradle
WORKDIR /home/gradle
RUN git clone --depth 1 https://github.com/serezhka/java-airplay-server-examples.git \
    && cd java-airplay-server-examples/tcp-forwarder \
    && sed -i 's/server.name=srzhka/server.name=QuackPlay/' \
        src/main/resources/tcp-forwarder.properties \
    && gradle bootJar
WORKDIR /home/gradle/java-airplay-server-examples/tcp-forwarder/build/libs
CMD ["java", "-jar", "tcp-forwarder-0.0.1-SNAPSHOT.jar"]
